name: expense
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.2.0
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  intl: ^0.18.0
  month_picker_dialog: ^2.0.2
  pie_menu: ^1.3.0
  flutter_colorpicker: ^1.0.3
  awesome_snackbar_content: ^0.1.3
  drop_down_list_menu: ^0.0.9
  omni_datetime_picker: ^1.0.7
  flutter_flushbar: ^0.0.2
  external_path: ^1.0.3
  flutter_spinkit: ^5.2.0
  flutter_local_notifications: ^14.1.1
  flutter_background_service: ^3.0.1
  android_alarm_manager: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf

  - family: Oswald
    fonts:
      - asset: assets/fonts/Oswald-Regular.ttf

  - family: CustomIcons
    fonts:
      - asset: assets/fonts/CustomIcons.ttf
