name: akaontyit
description: "Expense managment app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.2.0
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  permission_handler: ^11.4.0
  intl: ^0.19.0
  month_picker_dialog: ^6.0.3
  pie_menu: ^3.2.7
  flutter_colorpicker: ^1.0.3
  awesome_snackbar_content: ^0.1.1
  drop_down_list_menu: ^0.0.9
  omni_datetime_picker: ^2.1.1
  flutter_flushbar: ^0.0.2
  external_path: ^2.2.0
  flutter_spinkit: ^5.2.0
  currency_textfield: ^4.0.0
  awesome_dialog: ^3.2.1
  flutter_screen_lock: ^9.2.1
  local_auth: ^2.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf

  - family: Oswald
    fonts:
      - asset: assets/fonts/Oswald-Regular.ttf

  - family: CustomIcons
    fonts:
      - asset: assets/fonts/CustomIcons.ttf
